apiVersion: v1
kind: Service
metadata:
  name: {{ include "umbrella-chart.fullname" . }}
  labels:
    app: {{ template "umbrella-chart.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "umbrella-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
